name: Release

on:
  release:
    types: [published]

jobs:

  pypi:
    permissions:
      id-token: write
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          python -m build --wheel .

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1