name: 'Testing'
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  linting:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing requirements
        run: pip3 install -r requirements_dev.txt

      - name: Linting package
        run: |
          black --check splice
          black --check tests

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing requirements
        run: pip3 install -r requirements_dev.txt


      - name: Testing with pytest
        run: |
          pytest -vv tests
